# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='lname',
            new_name='last_name',
        ),
    ]
